##
# Fichier : services.yml
# Chemin : bastien59960/reactions/config/development/services.yml
# Auteur : Bastien (bastien59960)
# GitHub : https://github.com/bastien59960/reactions
#
# Rôle :
# Ce fichier active le mode debug pour le conteneur de services de Symfony.
# Il sera automatiquement chargé par phpBB si le mode DEBUG est activé
# dans le fichier config.php du forum.
#
# @copyright (c) 2025 Bastien59960
# @license GNU General Public License, version 2 (GPL-2.0)
##

parameters:
    # Active le mode debug du conteneur de services.
    # C'est le paramètre le plus important pour obtenir des erreurs claires.
    debug.container: true
