##
# Fichier : parameters.yml
# Chemin : bastien59960/reactions/config/parameters.yml
# Auteur : Bastien (bastien59960)
# GitHub : https://github.com/bastien59960/reactions
#
# Rôle :
# Ce fichier définit les paramètres utilisés par l'extension, notamment les noms
# des tables de la base de données.
#
# @copyright (c) 2025 Bastien59960
# @license GNU General Public License, version 2 (GPL-2.0)
##

parameters:
    # =============================================================================
    # TABLES DE BASE DE DONNÉES
    # =============================================================================

    # Table principale des réactions
    tables.post_reactions: '%core.table_prefix%post_reactions'

    # Table des sujets (référence)
    tables.topics: '%core.table_prefix%topics'

    # Table des forums (référence)
    tables.forums: '%core.table_prefix%forums'
